version: '4'
services:

  gateway:
    restart: always
    networks:
      - backend
    build:
      context: ./Gateway
      dockerfile: Dockerfile.gateway
    ports:
      - "8090:8090"

  full_recipes_service:
    restart: always
    networks:
      - backend
    build:
      context: ./MicroServiceRecipes
      dockerfile: Dockerfile.full_recipes

  search_engine_service:
    restart: always
    networks:
      - backend
    build:
      context: ./SearchEngine
      dockerfile: Dockerfile.search_engine

  commentary_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceCommentary
      dockerfile: Dockerfile.commentary

  recipes_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceRecipes
      dockerfile: Dockerfile.recipes

  score_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceScore
      dockerfile: Dockerfile.score

  top_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceTop
      dockerfile: Dockerfile.top

  user_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceUser
      dockerfile: Dockerfile.user

networks:
  backend:
    driver: bridge
