version: '4'
# https://graspingtech.com/docker-compose-demo/
services:

  gateway:
    restart: always
    networks:
      - backend
    build:
      context: ./Gateway
      dockerfile: Dockerfile.gateway
    ports:
      - "8090:8090"

  full_recipes_service:
    restart: always
    networks:
      - backend
    build:
      context: ./MicroServiceRecipes
      dockerfile: Dockerfile.full_recipes
    ports:
      - "8086:8086"

  search_engine_service:
    restart: always
    networks:
      - backend
    build:
      context: ./SearchEngine
      dockerfile: Dockerfile.search_engine
    ports:
      - "8087:8087"

  commentary_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceCommentary
      dockerfile: Dockerfile.commentary
    ports:
      - "8083:8083"

  recipes_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceRecipes
      dockerfile: Dockerfile.recipes
    ports:
      - "8082:8082"

  score_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceScore
      dockerfile: Dockerfile.score
    ports:
      - "8084:8084"

  top_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceTop
      dockerfile: Dockerfile.top
    ports:
      - "8085:8085"

  user_service:
    restart: always
    networks:
      - backend
    build:
      context: ./ServiceUser
      dockerfile: Dockerfile.user
    ports:
      - "8081:8081"

networks:
  backend:
    driver: bridge
