FROM node:12-alpine

ENV PREFIX=api
ENV VERSION=1
ENV PORT=8090
ENV SERVICE_USER=http://user_service:8081/users
ENV SERVICE_RECIPE=http://recipes_service:8082/recipes
ENV SERVICE_COMMENTARY=http://commentary_service:8083/commentaries
ENV SERVICE_SCORE=http://score_service:8084/scores
ENV SERVICE_TOP=http://top_service:8085/top
ENV SERVICE_FULL_RECIPE=http://full_recipes_service:8086/recipes
ENV SERVICE_SEARCH_ENGINE=http://search_engine_service:8087/search_engine
ENV SERVICE_FAVOURITES=http://favourites_service:8088/favourites
ENV SERVICE_CALENDAR=http://calendar_service:8089/calendar

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY package*.json ./

RUN npm config set unsafe-perm true

RUN npm install -g typescript
RUN npm install -g ts-node
USER node
RUN npm install

COPY --chown=node:node . .
RUN npm run build

CMD [ "npm", "start" ]